package me.koz.beachmode.challenge;

public enum ChallengeType {

    DIAMOND_MINED, EMERALD_MINED, IRON_MINED,
    GOLD_MINED, SKELETON_KILLED, ZOMBIE_KILLED,
    COW_KILLED, BLOCK_MINED, BLOCK_PLACED, PLAYER_KILLED,

}