purchased: "&aSuccess"
not-enough-money: "&cYou don't have enough money. You have %player_money% gold and you need %needed% gold"

category:
  title: "&7Select a Category"
  size: 45
  items:
    1:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 0
    2:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 1
    3:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 2
    4:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 3
    5:
      item: "PLAYER_HEAD"
      name: "%player%&e's Statistics"
      lore:
        - ""
        - "&6Balance: &e%gold%"
        - ""
      slot: 4
    6:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 5
    7:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 6
    8:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 7
    9:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 8
    10:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 44
    11:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 43
    12:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 42
    13:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 41
    14:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 40
    15:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 39
    16:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 38
    17:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 37
    18:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 36
    30:
      item: "EMERALD"
      name: "&eRanks"
      lore:
        - ""
        - "&7&oA place to buy ranks"
        - ""
        - "&e&lCLICK TO OPEN"
      slot: 13
    31:
      item: "TRIPWIRE_HOOK"
      name: "&6Crate Keys"
      lore:
        - ""
        - "&7&oA place to buy crate keys"
        - ""
        - "&6&lCLICK TO OPEN"
      slot: 21
    32:
      item: "END_CRYSTAL"
      name: "&aPerks"
      lore:
        - ""
        - "&7&oA place to buy perks"
        - ""
        - "&a&lCLICK TO OPEN"
      slot: 23
    33:
      item: "NAME_TAG"
      name: "&bMisc"
      lore:
        - ""
        - "&7&oA place to buy mics"
        - ""
        - "&b&lCLICK TO OPEN"
      slot: 31

ranks:
  title: "Ranks"
  size: 45
  open: "&eRanks"
  items:
    1:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 0
      price: 0
    2:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 1
      price: 0
    3:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 2
      price: 0
    4:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 3
      price: 0
    5:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 4
      price: 0
    6:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 5
      price: 0
    7:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 6
      price: 0
    8:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 7
      price: 0
    9:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 8
      price: 0
    10:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 44
      price: 0
    11:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 43
      price: 0
    12:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 42
      price: 0
    13:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 41
      price: 0
    14:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 40
      price: 0
    15:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 39
      price: 0
    16:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 38
      price: 0
    17:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 37
      price: 0
    18:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 36
      price: 0
    19:
      item: "BEDROCK"
      name: "&7&lEXAMPLE RANK"
      lore:
        - ""
        - "&7&oBecome a example rank"
        - ""
        - "&e&lPRICE: &f1000"
        - "&e&lCLICK TO PURCHASE"
      slot: 11
      price: 1000
      command: "lp user %player% parent set example"
crates:
  title: "Crates"
  size: 45
  open: "&6Crate Keys"
  items:
    1:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 0
    2:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 1
    3:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 2
    4:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 3
    5:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 4
    6:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 5
    7:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 6
    8:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 7
    9:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 8
    10:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 44
    11:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 43
    12:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 42
    13:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 41
    14:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 40
    15:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 39
    16:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 38
    17:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 37
    18:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 36
    30:
      item: "TRIPWIRE_HOOK"
      name: "&dEXAMPLE CRATE"
      lore:
        - ""
        - "&7Right click to obtain a &DEXAMPLE CRATE"
        - ""
        - "&e&lPRICE: &f100"
        - "&e&lCLICK TO PURCHASE"
        - ""
      slot: 19
      price: 100
      command: "cr givekey %player% example 1"

perks:
  title: "Perks"
  size: 45
  open: "&aPerks"
  items:
    1:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 0
    2:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 1
    3:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 2
    4:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 3
    5:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 4
    6:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 5
    7:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 6
    8:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 7
    9:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 8
    10:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 44
    11:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 43
    12:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 42
    13:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 41
    14:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 40
    15:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 39
    16:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 38
    17:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 37
    18:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 36
    30:
      item: "DIAMOND_BOOTS"
      name: "&aJellyLegs Perk"
      lore:
        - ""
        - "&7Perk is disabling fall damage"
        - ""
        - "&e&lPRICE: &f100"
        - "&e&lCLICK TO PURCHASE"
        - ""
      slot: 19
      price: 100
      command: "lp user %player% permission set beach.jellylegs"

misc:
  title: "Misc"
  size: 45
  open: "&bMisc"
  items:
    1:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 0
    2:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 1
    3:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 2
    4:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 3
    5:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 4
    6:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 5
    7:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 6
    8:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
      slot: 7
    9:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 8
    10:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 44
    11:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 43
    12:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 42
    13:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 41
    14:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 40
    15:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 39
    16:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 38
    17:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 37
    18:
      item: "GRAY_STAINED_GLASS_PANE"
      name: ""
      lore:
        - ""
        - ""
      slot: 36
    30:
      item: "EXPERIENCE_BOTTLE"
      name: "&aEXP Booster"
      lore:
        - ""
        - "&7This perk will give you 2x EXP for 1 Hour."
        - ""
        - "&e&lPRICE: &f100"
        - "&e&lCLICK TO PURCHASE"
        - ""
      slot: 19
      price: 100
      command: "xpbooster give %player% 1h"

messages:
  wrong-usage:
    - "&f&m----------------------------------"
    - "&e/goldadmin set <player> <amount>"
    - "&e/goldadmin add <player> <amount>"
    - "&e/goldadmin remove <player> <amount>"
    - "&e/goldadmin check <player>"
    - "&f&m----------------------------------"
  set: "&aYou have set %amount% coins to %player%"
  add: "&aYou have added %amount% coins to %player%"
  remove: "&aYou have removed %amount% coins from %player%"
  check: "&a%player% has %amount% of gold"

chat-format: "%rank% %player% %message%"
chat-format-team: "%team% %rank% %player% %message%"

death:
  message: "&c%player% was slained by %killer%"