name: Core
version: '${project.version}'
main: me.koz.beachmode.Core
api-version: 1.19
description: Made by KacperM
softdepend:
  - MVdWPlaceholderAPI
commands:
  goldshop:
  goldadmin:
  wild:
    aliases: [rtp]
  ct:
  cc:
  team:
    aliases: [t]
  challenge: